import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { DashboardSidebar } from "@/components/Sidebar";
import DashboardHeader from "@/components/DashboardHeader";
import AppProvider from "@/provider/AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans")}>
      <body className="antialiased">
        <div className="flex h-screen overflow-hidden">
          {/* Sidebar */}
          <DashboardSidebar />

          {/* Main Content */}
          <div className="flex flex-1 shrink-0 flex-col bg-[#F8FAFC] ">
            {/* Top Header */}
            <DashboardHeader />

            {/* Page Content */}
            <main className="flex-1 overflow-y-auto scrollbar-hide">
              <AppProvider>{children}</AppProvider>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
