import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { DashboardSidebar } from "@/components/Sidebar";
import DashboardHeader from "@/components/DashboardHeader";
import AppProvider from "@/provider/AppProvider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans")}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen overflow-hidden">
          {/* Sidebar */}
          <DashboardSidebar />

          {/* Main Content */}
          <div className="flex flex-1 shrink-0 flex-col bg-[#F8FAFC] ">
            {/* Top Header */}
            <DashboardHeader  />

            {/* Page Content */}
            <main className="flex-1 overflow-y-auto scrollbar-hide">
              <AppProvider>
                {children}
              </AppProvider>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
